# Site settings
title: The Panama Papers
sub_title: Politicians, Criminals, and the Rogue Industry That Hides Their Cash

description: > # this means to ignore newlines until "baseurl:"
    Panama papers description...

baseurl: "" # the subpath of your site, e.g. /blog/

url: https://jv4j7kwhtudx5qft.investigativecenters.org  # with the https protocol
enforce_ssl: jv4j7kwhtudx5qft.investigativecenters.org   # without any protocol

twitter_username: AfricanCIR
github_username:  ANCIR
email:            info@investigativecentres.org

google_analytics: UA-63787251-3

# Build settings
markdown: kramdown
