# Site settings
title: The Panama Papers
sub_title: Politicians, Criminals, and the Rogue Industry That Hides Their Cash

description: > # this means to ignore newlines until "baseurl:"
    The Panama Papers is an unprecedented investigation that reveals the offshore links of some of the globe’s most prominent figures

baseurl: "" # the subpath of your site, e.g. /blog/

url: https://panamapapers.investigativecenters.org  # with the https protocol
enforce_ssl: panamapapers.investigativecenters.org   # without any protocol

twitter_username: AfricanCIR
github_username:  ANCIR
email:            info@investigativecentres.org

google_analytics: UA-63787251-5

# Build settings
markdown: kramdown
